using System;
using System.Collections.Generic;
using System.Text;

namespace Recipes_MX.Logic.Model.BigOvenAPI
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.34014
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.18020.
    // 


    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class RecipeSearchResult
    {

        private ushort resultCountField;

        private RecipeSearchResultRecipeInfo[] resultsField;

        /// <remarks/>
        public ushort ResultCount
        {
            get
            {
                return this.resultCountField;
            }
            set
            {
                this.resultCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RecipeInfo", IsNullable = false)]
        public RecipeSearchResultRecipeInfo[] Results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
    }

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RecipeSearchResultRecipeInfo
    {

        private uint recipeIDField;

        private string titleField;

        private string cuisineField;

        private string categoryField;

        private string subcategoryField;

        private float starRatingField;

        private string webURLField;

        private string imageURLField;

        private string imageURL120Field;

        private byte reviewCountField;

        private RecipeSearchResultRecipeInfoPoster posterField;

        /// <remarks/>
        public uint RecipeID
        {
            get
            {
                return this.recipeIDField;
            }
            set
            {
                this.recipeIDField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Cuisine
        {
            get
            {
                return this.cuisineField;
            }
            set
            {
                this.cuisineField = value;
            }
        }

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public string Subcategory
        {
            get
            {
                return this.subcategoryField;
            }
            set
            {
                this.subcategoryField = value;
            }
        }

        /// <remarks/>
        public float StarRating
        {
            get
            {
                return this.starRatingField;
            }
            set
            {
                this.starRatingField = value;
            }
        }

        /// <remarks/>
        public string WebURL
        {
            get
            {
                return this.webURLField;
            }
            set
            {
                this.webURLField = value;
            }
        }

        /// <remarks/>
        public string ImageURL
        {
            get
            {
                return this.imageURLField;
            }
            set
            {
                this.imageURLField = value;
            }
        }

        /// <remarks/>
        public string ImageURL120
        {
            get
            {
                return this.imageURL120Field;
            }
            set
            {
                this.imageURL120Field = value;
            }
        }

        /// <remarks/>
        public byte ReviewCount
        {
            get
            {
                return this.reviewCountField;
            }
            set
            {
                this.reviewCountField = value;
            }
        }

        /// <remarks/>
        public RecipeSearchResultRecipeInfoPoster Poster
        {
            get
            {
                return this.posterField;
            }
            set
            {
                this.posterField = value;
            }
        }
    }

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RecipeSearchResultRecipeInfoPoster
    {

        private uint userIDField;

        private string userNameField;

        /// <remarks/>
        public uint UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }


    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Recipe
    {

        private uint recipeIDField;

        private string titleField;

        private string descriptionField;

        private string cuisineField;

        private string categoryField;

        private string subcategoryField;

        private string primaryIngredientField;

        private float starRatingField;

        private string webURLField;

        private string imageURLField;

        private RecipePoster posterField;

        private RecipeIngredient[] ingredientsField;

        private string instructionsField;

        private float? yieldNumberField;

        private string yieldUnitField;

        private float? totalMinutesField;

        private float? activeMinutesField;

        private RecipeNutritionInfo nutritionInfoField;

        /// <remarks/>
        public uint RecipeID
        {
            get
            {
                return this.recipeIDField;
            }
            set
            {
                this.recipeIDField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Cuisine
        {
            get
            {
                return this.cuisineField;
            }
            set
            {
                this.cuisineField = value;
            }
        }

        /// <remarks/>
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public string Subcategory
        {
            get
            {
                return this.subcategoryField;
            }
            set
            {
                this.subcategoryField = value;
            }
        }

        /// <remarks/>
        public string PrimaryIngredient
        {
            get
            {
                return this.primaryIngredientField;
            }
            set
            {
                this.primaryIngredientField = value;
            }
        }

        /// <remarks/>
        public float StarRating
        {
            get
            {
                return this.starRatingField;
            }
            set
            {
                this.starRatingField = value;
            }
        }

        /// <remarks/>
        public string WebURL
        {
            get
            {
                return this.webURLField;
            }
            set
            {
                this.webURLField = value;
            }
        }

        /// <remarks/>
        public string ImageURL
        {
            get
            {
                return this.imageURLField;
            }
            set
            {
                this.imageURLField = value;
            }
        }

        /// <remarks/>
        public RecipePoster Poster
        {
            get
            {
                return this.posterField;
            }
            set
            {
                this.posterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Ingredient", IsNullable = false)]
        public RecipeIngredient[] Ingredients
        {
            get
            {
                return this.ingredientsField;
            }
            set
            {
                this.ingredientsField = value;
            }
        }

        /// <remarks/>
        public string Instructions
        {
            get
            {
                return this.instructionsField;
            }
            set
            {
                this.instructionsField = value;
            }
        }

        /// <remarks/>
        public float? YieldNumber
        {
            get
            {
                return this.yieldNumberField;
            }
            set
            {
                this.yieldNumberField = value;
            }
        }

        /// <remarks/>
        public string YieldUnit
        {
            get
            {
                return this.yieldUnitField;
            }
            set
            {
                this.yieldUnitField = value;
            }
        }

        /// <remarks/>
        public float? TotalMinutes
        {
            get
            {
                return this.totalMinutesField;
            }
            set
            {
                this.totalMinutesField = value;
            }
        }

        /// <remarks/>
        public float? ActiveMinutes
        {
            get
            {
                return this.activeMinutesField;
            }
            set
            {
                this.activeMinutesField = value;
            }
        }

        /// <remarks/>
        public RecipeNutritionInfo NutritionInfo
        {
            get
            {
                return this.nutritionInfoField;
            }
            set
            {
                this.nutritionInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RecipePoster
    {

        private uint userIDField;

        private string userNameField;

        private string imageURL48Field;

        /// <remarks/>
        public uint UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string ImageURL48
        {
            get
            {
                return this.imageURL48Field;
            }
            set
            {
                this.imageURL48Field = value;
            }
        }
    }

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RecipeIngredient
    {

        private uint ingredientIDField;

        private byte displayIndexField;

        private bool isHeadingField;

        private string nameField;

        private string hTMLNameField;

        private decimal quantityField;

        private string displayQuantityField;

        private string unitField;

        private decimal metricQuantityField;

        private string metricDisplayQuantityField;

        private string metricUnitField;

        private string preparationNotesField;

        private RecipeIngredientIngredientInfo ingredientInfoField;

        private bool isLinkedField;

        /// <remarks/>
        public uint IngredientID
        {
            get
            {
                return this.ingredientIDField;
            }
            set
            {
                this.ingredientIDField = value;
            }
        }

        /// <remarks/>
        public byte DisplayIndex
        {
            get
            {
                return this.displayIndexField;
            }
            set
            {
                this.displayIndexField = value;
            }
        }

        /// <remarks/>
        public bool IsHeading
        {
            get
            {
                return this.isHeadingField;
            }
            set
            {
                this.isHeadingField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string HTMLName
        {
            get
            {
                return this.hTMLNameField;
            }
            set
            {
                this.hTMLNameField = value;
            }
        }

        /// <remarks/>
        public decimal Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string DisplayQuantity
        {
            get
            {
                return this.displayQuantityField;
            }
            set
            {
                this.displayQuantityField = value;
            }
        }

        /// <remarks/>
        public string Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }

        /// <remarks/>
        public decimal MetricQuantity
        {
            get
            {
                return this.metricQuantityField;
            }
            set
            {
                this.metricQuantityField = value;
            }
        }

        /// <remarks/>
        public string MetricDisplayQuantity
        {
            get
            {
                return this.metricDisplayQuantityField;
            }
            set
            {
                this.metricDisplayQuantityField = value;
            }
        }

        /// <remarks/>
        public string MetricUnit
        {
            get
            {
                return this.metricUnitField;
            }
            set
            {
                this.metricUnitField = value;
            }
        }

        /// <remarks/>
        public string PreparationNotes
        {
            get
            {
                return this.preparationNotesField;
            }
            set
            {
                this.preparationNotesField = value;
            }
        }

        /// <remarks/>
        public RecipeIngredientIngredientInfo IngredientInfo
        {
            get
            {
                return this.ingredientInfoField;
            }
            set
            {
                this.ingredientInfoField = value;
            }
        }

        /// <remarks/>
        public bool IsLinked
        {
            get
            {
                return this.isLinkedField;
            }
            set
            {
                this.isLinkedField = value;
            }
        }
    }

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RecipeIngredientIngredientInfo
    {

        private string nameField;

        private string departmentField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class RecipeNutritionInfo
    {

        private string singularYieldUnitField;

        private byte totalCaloriesField;

        private byte totalFatField;

        private byte caloriesFromFatField;

        private byte totalFatPctField;

        private byte satFatField;

        private byte satFatPctField;

        private byte monoFatField;

        private byte polyFatField;

        private byte transFatField;

        private byte cholesterolField;

        private byte cholesterolPctField;

        private byte sodiumField;

        private byte sodiumPctField;

        private byte potassiumField;

        private byte potassiumPctField;

        private byte totalCarbsField;

        private byte totalCarbsPctField;

        private byte dietaryFiberField;

        private byte dietaryFiberPctField;

        private byte sugarField;

        private byte proteinField;

        private byte proteinPctField;

        /// <remarks/>
        public string SingularYieldUnit
        {
            get
            {
                return this.singularYieldUnitField;
            }
            set
            {
                this.singularYieldUnitField = value;
            }
        }

        /// <remarks/>
        public byte TotalCalories
        {
            get
            {
                return this.totalCaloriesField;
            }
            set
            {
                this.totalCaloriesField = value;
            }
        }

        /// <remarks/>
        public byte TotalFat
        {
            get
            {
                return this.totalFatField;
            }
            set
            {
                this.totalFatField = value;
            }
        }

        /// <remarks/>
        public byte CaloriesFromFat
        {
            get
            {
                return this.caloriesFromFatField;
            }
            set
            {
                this.caloriesFromFatField = value;
            }
        }

        /// <remarks/>
        public byte TotalFatPct
        {
            get
            {
                return this.totalFatPctField;
            }
            set
            {
                this.totalFatPctField = value;
            }
        }

        /// <remarks/>
        public byte SatFat
        {
            get
            {
                return this.satFatField;
            }
            set
            {
                this.satFatField = value;
            }
        }

        /// <remarks/>
        public byte SatFatPct
        {
            get
            {
                return this.satFatPctField;
            }
            set
            {
                this.satFatPctField = value;
            }
        }

        /// <remarks/>
        public byte MonoFat
        {
            get
            {
                return this.monoFatField;
            }
            set
            {
                this.monoFatField = value;
            }
        }

        /// <remarks/>
        public byte PolyFat
        {
            get
            {
                return this.polyFatField;
            }
            set
            {
                this.polyFatField = value;
            }
        }

        /// <remarks/>
        public byte TransFat
        {
            get
            {
                return this.transFatField;
            }
            set
            {
                this.transFatField = value;
            }
        }

        /// <remarks/>
        public byte Cholesterol
        {
            get
            {
                return this.cholesterolField;
            }
            set
            {
                this.cholesterolField = value;
            }
        }

        /// <remarks/>
        public byte CholesterolPct
        {
            get
            {
                return this.cholesterolPctField;
            }
            set
            {
                this.cholesterolPctField = value;
            }
        }

        /// <remarks/>
        public byte Sodium
        {
            get
            {
                return this.sodiumField;
            }
            set
            {
                this.sodiumField = value;
            }
        }

        /// <remarks/>
        public byte SodiumPct
        {
            get
            {
                return this.sodiumPctField;
            }
            set
            {
                this.sodiumPctField = value;
            }
        }

        /// <remarks/>
        public byte Potassium
        {
            get
            {
                return this.potassiumField;
            }
            set
            {
                this.potassiumField = value;
            }
        }

        /// <remarks/>
        public byte PotassiumPct
        {
            get
            {
                return this.potassiumPctField;
            }
            set
            {
                this.potassiumPctField = value;
            }
        }

        /// <remarks/>
        public byte TotalCarbs
        {
            get
            {
                return this.totalCarbsField;
            }
            set
            {
                this.totalCarbsField = value;
            }
        }

        /// <remarks/>
        public byte TotalCarbsPct
        {
            get
            {
                return this.totalCarbsPctField;
            }
            set
            {
                this.totalCarbsPctField = value;
            }
        }

        /// <remarks/>
        public byte DietaryFiber
        {
            get
            {
                return this.dietaryFiberField;
            }
            set
            {
                this.dietaryFiberField = value;
            }
        }

        /// <remarks/>
        public byte DietaryFiberPct
        {
            get
            {
                return this.dietaryFiberPctField;
            }
            set
            {
                this.dietaryFiberPctField = value;
            }
        }

        /// <remarks/>
        public byte Sugar
        {
            get
            {
                return this.sugarField;
            }
            set
            {
                this.sugarField = value;
            }
        }

        /// <remarks/>
        public byte Protein
        {
            get
            {
                return this.proteinField;
            }
            set
            {
                this.proteinField = value;
            }
        }

        /// <remarks/>
        public byte ProteinPct
        {
            get
            {
                return this.proteinPctField;
            }
            set
            {
                this.proteinPctField = value;
            }
        }
    }

}
